### ISSUE TITLE
RHDH Cypress setup and Guest happy path automation

### ISSUE THREAD

**Issue by subhashkhileri** [janus-idp/showcase-e2e#46]
**RHDH Cypress setup and Guest happy path automation**

[Test Plan](https://docs.google.com/spreadsheets/d/1Hx10G_I2ipcL62qeFFxa90Lipd-54QrdcvNSROCGOrk/edit#gid=926455087)

Test with Guest Sign-in
9) Enter as a Guest
    9.a) Verify the Homepage renders with Search Bar, Quick Access and Starred Entities
    9.b) Verify Catalog page renders with no components
    9.c) Verify that all users in your Github Organization have been ingested into the Catalog Page (filter for Kind = User)
    9.d) Verify all 12 GPTs appear in the Create... page
    9.e) Verify Profile is Guest in the Settings page (Ensure backstage identity's User Entity is user:default/guest)
    9.f) Sign Out and Verify that you return to the Sign-in page

**Comment by kadel** [comment]
this is tracked in jira
